# Generated by Django 4.2.15 on 2024-09-27 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 27, 20, 18, 33, 944733, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
