# Generated by Django 4.2.15 on 2024-09-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_shippingaddress_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='created_at',
        ),
    ]
