# Generated by Django 4.2.15 on 2024-09-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_shippingaddress_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
